### ISSUE TITLE
PHP 5.5 (PPA) is deprecated/EOL

### ISSUE THREAD

**Issue by dennisdegreef** [AmsterdamPHP/meetup-raffle-machine#28]
Since PHP 5.5 is EOL, the PPA is also deprecated.
If we upgrade PHP, should we upgrade to PHP 7 ?

```
dev :: /vagrant » php -v
PHP 5.5.37-1+deprecated+dontuse+deb.sury.org~trusty+1 (cli) (built: Jun 24 2016 08:29:49) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
dev :: /vagrant » 
```

**Comment by dennisdegreef** [comment]
I also can't install PHPUnit due to the version constraint

```
dev :: /vagrant » composer require --dev phpunit/phpunit   
Using version ^4.8 for phpunit/phpunit
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sebastian/version 2.0.0 requires php >=5.6 -> your PHP version (5.5.37) does not satisfy that requirement.
    - sebastian/version 2.0.0 requires php >=5.6 -> your PHP version (5.5.37) does not satisfy that requirement.
    - sebastian/version 2.0.0 requires php >=5.6 -> your PHP version (5.5.37) does not satisfy that requirement.
    - Installation request for sebastian/version (locked at 2.0.0) -> satisfiable by sebastian/version[2.0.0].


Installation failed, reverting ./composer.json to its original content.
dev :: /vagrant » 

```

**Comment by rdohms** [comment]
We are in the process of making sure everything works on PHP7 to migrate our servers, sounds like a good place to start.

**Comment by dennisdegreef** [comment]
See https://github.com/heybigname/ansible/pull/18
Can we make overrides in our configuration to point to `php7.1` ?

**Comment by dennisdegreef** [comment]
https://github.com/AmsterdamPHP/meetup-raffle-machine/pull/29/commits/f5865a24b7047217febdd8d5a5f4d6149e3ba086

This commit uses the updated submodule, so it's now running PHP 5.6 using the deprecated 5.6 repository (at least no 5.5 anymore).

If the heybigname/ansible project points to the latest PPA repository, we should somehow be able to pick 7.x instead of the default 5.6. (not too familiar with ansible though, not sure if we can specify overrides?)
